import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start`: a minified edge-runtime bundle. Git ignores it, but eslint
    // walks it anyway and reports ~150 errors in machine-written code whenever the local stack
    // is running. Not ours to lint.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
